---
title: "Lab2 - Regressão Linear"
output: 
  html_document:
    toc : true
    toc_float: true
    
---

```{r setup, include=FALSE}
library(dplyr)
library(reshape2)
library(GGally)
library(ggplot2)
library(corrplot)
```

## Utilizando regressão linear para explicar o desempenho acadêmico.

## Lendo os dados

```{r}
dados <- read.csv("dados/graduados.csv")
```


## Conhecendo os dados
```{r}
graduados <- dados %>%
  arrange(matricula)

graduados.clean <- graduados %>%
  filter(!is.na(media))

graduados.cra <- graduados.clean %>%
  group_by(matricula) %>%
  mutate(cra.contrb = media*creditos) %>%
  summarise(cra = sum(cra.contrb)/sum(creditos))

graduados.model.input <- graduados.clean %>%
  group_by(matricula, disciplina) %>%
  filter(media == max(media))%>%
  ungroup() %>%
  select(matricula, disciplina, media) %>%
  mutate(disciplina = as.factor(gsub(" ", ".", disciplina))) %>%
  dcast(matricula ~disciplina, mean) %>%
  merge(graduados.cra)

```



## Analisando Primeiro Periodo
```{r}
primeiro.periodo <- graduados.model.input %>%
  select(matricula, Cálculo.Diferencial.e.Integral.I, Álgebra.Vetorial.e.Geometria.Analítica, Leitura.e.Produção.de.Textos, Programação.I, Introdução.à.Computação, Laboratório.de.Programação.I, cra)

primeiro.periodo <- na.omit(primeiro.periodo)
primeiro.periodo <- primeiro.periodo %>% select(-matricula)

ggpairs(primeiro.periodo)

df1 <- melt(primeiro.periodo)

ggplot(df1,aes(x = value)) + 
    facet_wrap(~variable, scales = "free_x") + 
    geom_histogram()
```

### Analisando Matriz de correlação
```{r}
correlationMatrix1 <- cor(primeiro.periodo)
print(correlationMatrix1)
corrplot(correlationMatrix1, method="circle", type="lower", order="hclust", addCoef.col = "black")
```

## Modelo
```{r}

modelo.primeiro.periodo <- lm(cra ~ Laboratório.de.Programação.I + Programação.I + Introdução.à.Computação + Cálculo.Diferencial.e.Integral.I + Álgebra.Vetorial.e.Geometria.Analítica + Leitura.e.Produção.de.Textos, primeiro.periodo)
modelo.primeiro.periodo


library(broom)
tidy(modelo.primeiro.periodo, conf.int = TRUE)
```


## Analisando Segundo Periodo
```{r}
segundo.periodo <-  graduados.model.input %>%
  select(matricula, Cálculo.Diferencial.e.Integral.II, Matemática.Discreta, Programação.II, Teoria.dos.Grafos, Fundamentos.de.Física.Clássica, Laboratório.de.Programação.II, cra)

segundo.periodo <- na.omit(segundo.periodo)
segundo.periodo <- segundo.periodo %>% select(-matricula)

ggpairs(segundo.periodo)

df2 <- melt(segundo.periodo)

ggplot(df2,aes(x = value)) + 
    facet_wrap(~variable, scales = "free_x") + 
    geom_histogram()

```

### Analisando Matriz de correlação
```{r}
correlationMatrix2 <- cor(segundo.periodo)
print(correlationMatrix2)
corrplot(correlationMatrix2, method="circle", type="lower", order="hclust", addCoef.col = "black")
```

## Modelo
```{r}

modelo.segundo.periodo <- lm(cra ~ Cálculo.Diferencial.e.Integral.II + Matemática.Discreta + Programação.II + Teoria.dos.Grafos+ Fundamentos.de.Física.Clássica+ Laboratório.de.Programação.II, segundo.periodo)
modelo.primeiro.periodo


library(broom)
tidy(modelo.primeiro.periodo, conf.int = TRUE)
```